#pragma once

#define NUM_IA_MESH_LAYOUT 2
#define IA_MESH_LAYOUT {\
	{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},\
	{"UV", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },}


#define NUM_IA_MESH_SIMPLE_LAYOUT 1
#define IA_MESH_SIMPLE_LAYOUT {\
	{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0}}