#pragma once

#define NUM_IA_MESH_LAYOUT 2
#define IA_MESH_LAYOUT {\
	{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},\
	{"TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },}


#define NUM_IA_MESH_SIMPLE_LAYOUT 1
#define IA_MESH_SIMPLE_LAYOUT {\
	{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0}}

#define NUM_IA_FULLSCREEN_QUAD_LAYOUT 1
#define IA_FULLSCREEN_QUAD_LAYOUT {\
	{"POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }}


#define BASE_COLOR_TEX_MESH_ARGUMENT_ID					101
#define METALLIC_TEX_MESH_ARGUMENT_ID					102
#define ROUGHNESS_TEX_MESH_ARGUMENT_ID					103
#define NORMAL_TEX_MESH_ARGUMENT_ID						104
#define MESH_CONSTANT_BUFFER_MESH_ARGUMENT_ID			105

#define PASS_MESH_ARGUMENTS_MAP_DEFINE {\
	 {PassType::GEOMETRY_PASS, \
		{{BASE_COLOR_TEX_MESH_ARGUMENT_ID, 3}, \
		 {METALLIC_TEX_MESH_ARGUMENT_ID, 4}, \
		 {ROUGHNESS_TEX_MESH_ARGUMENT_ID, 5}, \
		 {NORMAL_TEX_MESH_ARGUMENT_ID, 6}, \
		 {MESH_CONSTANT_BUFFER_MESH_ARGUMENT_ID, 1}}}, \
	 {PassType::EARLY_Z_PASS, \
		{{MESH_CONSTANT_BUFFER_MESH_ARGUMENT_ID, 1}}}, \
	 {PassType::SHADOW_PASS, \
		{{MESH_CONSTANT_BUFFER_MESH_ARGUMENT_ID, 0}}}, \
	 {PassType::LIGHTING_PASS, \
		{{MESH_CONSTANT_BUFFER_MESH_ARGUMENT_ID, 1}}}, \
 }

#define MAX_NUM_LIGHT_MAP								50