#pragma once

#include "Includes.h"

enum class PassType
{
	NONE = 0,
	SHADOW_PASS = 1,
	EARLY_Z_PASS = 2,
	GEOMETRY_PASS = 3,
	LIGHTING_PASS = 4,
	LIGHT_SHAFT_PRE_PASS = 5,
	LIGHT_FRUSTUM_DEBUG_PASS = 6,
	LIGHT_SHAFT_PASS = 7,
	SILHOUETTE_RENDER_PASS = 8,
};
